# library(devtools)
# library(usethis)
# library(repro)
# library(gitcreds)
# library(lintr)
# library(roxygen2)
# use_git()
# usethis::defunct()
# devtools::build("/Users/doedmond.sanou/Rmglasso/Rmglasso-main")
# devtools::check("/Users/doedmond.sanou/Rmglasso/Rmglasso-main")
# packagePath = "/Users/doedmond.sanou/Rmglasso/Rmglasso-main"
# lint_package(packagePath)
