library(devtools)
library(usethis)
# use_git()
# usethis::defunct()
# devtools::build("/Users/doedmond.sanou/Rmglasso/Rmglasso-main")
# devtools::check("/Users/doedmond.sanou/Rmglasso/Rmglasso-main")
